### ISSUE TITLE
lack the json file

### ISSUE THREAD

**Issue by Lalalalala-l** [QtacierP/PRIOR#8]
hello,mentor.can you provide the annotation.json,I meet some mistake.Please!

**Comment by QtacierP** [comment]
Which json file do you mean？If you say the json File in MimicCXR  dataset, maybe I cannot provide the exact file due to the license limitation. You can apply and download the file from the [homepage]（https://physionet.org/content/mimic-cxr/）, and run the preprocess scripts as shown in README.

**Comment by Lalalalala-l** [comment]
> Which json file do you mean？If you say the json File in MimicCXR dataset, maybe I cannot provide the exact file due to the license limitation. You can apply and download the file from the [homepage]（[https://physionet.org/content/mimic-cxr/）](https://physionet.org/content/mimic-cxr/%EF%BC%89), and run the preprocess scripts as shown in README.

Okay, thank you！

**Comment by QtacierP** [comment]
https://physionet.org/content/mimic-cxr-jpg/2.1.0/ You can download  images here

**Comment by Lalalalala-l** [comment]
> https://physionet.org/content/mimic-cxr-jpg/2.1.0/ You can download images here

Can you tell me the format of the data in the Json file? I have some problems here. I plan to modify them directly with the files that have been processed before. Thank you very much.

**Comment by QtacierP** [comment]
The json file is obtained by 
```
cd codes/
python prior/data/pretrain/mimiccxr.py build --root_image_path <image_dataset_path> --root_report_path <report_dataset_path> --save_path <dataset_json_path> --meta_csv_path <meta_csv_path>
```

as presented in the README :)

**Comment by Lalalalala-l** [comment]
> The json file is obtained by
> 
> ```
> cd codes/
> python prior/data/pretrain/mimiccxr.py build --root_image_path <image_dataset_path> --root_report_path <report_dataset_path> --save_path <dataset_json_path> --meta_csv_path <meta_csv_path>
> ```
> 
> as presented in the README :)

Thank you for your response. The issue has been resolved. Could you please tell me how to perform testing and evaluation?

**Comment by keepFaith-sdy** [comment]
Thank you for the great work! I still have an issue regarding the json file.

The "data.json" has been generated using the line you provided in README.md. However, when I reproduce this great work, there is an error that "  File "../PRIOR-main/codes/prior/data/pretrain/mimiccxr.py", line 132, in __getitem__
    label = self._get_meta(index)
  File "../PRIOR-main/codes/prior/data/pretrain/mimiccxr.py", line 126, in _get_meta
    return np.asanyarray(self.data_json[self.id_list[index]]['label']).astype(np.int64)
KeyError: 'label'"

I also review the json file, it does have "label". Could you please provide the correct data pre-processing? Thanks in advances and look forward to your suggestions!
